name: rel_extractor
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - accelerate=0.34.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - altair=5.0.1
  - aniso8601=9.0.1
  - annotated-types=0.6.0
  - anyio=4.2.0
  - aom=3.6.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - arrow-cpp=14.0.2
  - asttokens=2.0.5
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cachetools=5.3.3
  - cairo=1.16.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - cuda=11.8.0
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.6.68
  - cuda-driver-dev_linux-aarch64=12.6.68
  - cuda-gdb=12.6.68
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=12.6.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=12.6.68
  - cuda-nvml-dev=12.6.68
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.68
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=12.6.68
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-version=12.6
  - cuda-visual-tools=12.6.0
  - cycler=0.11.0
  - dataclasses-json=0.6.5
  - datasets=2.19.1
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - docker-pycreds=0.4.0
  - et_xmlfile=1.1.0
  - evaluate=0.4.0
  - executing=0.8.3
  - expat=2.6.2
  - ffmpeg=6.1.1
  - filelock=3.13.1
  - flask=2.2.5
  - flask-restful=0.3.10
  - flask-swagger-ui=4.11.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - greenlet=3.0.1
  - grpc-cpp=1.48.2
  - h11=0.14.0
  - harfbuzz=4.3.0
  - htbuilder=0.6.2
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - langchain=0.2.5
  - langchain-core=0.2.38
  - langchain-text-splitters=0.2.2
  - langsmith=0.1.111
  - lcms2=2.12
  - leptonica=1.82.0
  - lerc=3.0
  - libarchive=3.6.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.11.1.6
  - libcufile-dev=1.11.1.6
  - libcurand=10.3.7.68
  - libcurand-dev=10.3.7.68
  - libcurl=8.9.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvfatbin=12.6.68
  - libnvfatbin-dev=12.6.68
  - libnvjitlink=12.6.68
  - libnvjitlink-dev=12.6.68
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - marshmallow=3.19.0
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=2.0.4
  - more-itertools=10.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - nsight-compute=2024.3.1.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openai=0.28.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.0.14
  - orc=1.7.4
  - orjson=3.9.15
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandas-stubs=2.1.4.231227
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - plotly=5.22.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pybind11-abi=4
  - pycparser=2.21
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydeck=0.8.0
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.7.24
  - requests=2.32.3
  - responses=0.13.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.10.6
  - s2n=1.3.27
  - safetensors=0.4.4
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - send2trash=1.8.2
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=72.1.0
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.30
  - sqlite=3.45.3
  - st-annotated-text=4.0.0
  - stack_data=0.2.0
  - streamlit=1.38.0
  - sympy=1.13.2
  - tenacity=8.2.3
  - terminado=0.17.1
  - tesseract=5.2.0
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tokenizers=0.19.1
  - toml=0.10.2
  - toolz=0.12.0
  - torchvision=0.18.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - transformers=4.44.2
  - types-pytz=2022.4.0.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_inspect=0.9.0
  - tzdata=2024a
  - tzlocal=5.2
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - validators=0.18.2
  - wandb=0.16.6
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=2.2.3
  - wheel=0.43.0
  - widgetsnbextension=3.6.6
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5